[package]

name = "nom"
version = "4.0.0-alpha1"
authors = [ "contact@geoffroycouprie.com" ]
description = "A byte-oriented, zero-copy, parser combinators library"
license = "MIT"
repository = "https://github.com/Geal/nom"
readme = "README.md"
documentation = "http://rust.unhandledexpression.com/nom/"
keywords = ["parser", "parser-combinators", "parsing", "streaming", "bit"]
categories = ["parsing"]

include = [
  "CHANGELOG.md",
  "LICENSE",
  ".gitignore",
  ".travis.yml",
  "Cargo.toml",
  "src/*.rs",
  "tests/*.rs"
]

[features]
std = ["memchr/use_std"]
nightly = []
default = ["std"]
regexp = ["regex"]
regexp_macros = ["regexp", "lazy_static"]
verbose-errors = []

[dependencies.regex]
version = "^0.2"
optional = true

[dependencies.lazy_static]
version = "^1.0"
optional = true

[dependencies.memchr]
version = "^2.0"
default-features = false

#[dev-dependencies.bytes]
#git = "https://github.com/carllerche/bytes"
#rev = "a7d38e29"

[badges]
travis-ci = { repository = "Geal/nom" }
