name: CI

on: [push, pull_request]

env:
  RUST_MINVERSION: 1.37.0

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - 1.44.0

        features:
          - '--features "regexp"'

        include:
          - rust: stable
            features: ''
          - rust: stable
            features: '--features "std lexical regexp"'
          - rust: stable
            features: '--no-default-features'
          - rust: stable
            features: '--no-default-features --features "alloc"'
          - rust: nightly
            features: ''
          - rust: nightly
            features: '--no-default-features'
          - rust: nightly
            features: '--no-default-features --features "alloc"'

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install rust (${{ matrix.rust }})
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}

      - name: Build
        run: cargo build --verbose ${{ matrix.features }}

      - name: Test
        run: cargo test --verbose ${{ matrix.features }}

  minrust:
    name: Test MSRV
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install rust (${{ env.RUST_MINVERSION }})
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ env.RUST_MINVERSION }}

      - name: Build
        run: cargo build --verbose --no-default-features --features "regexp lexical"

      - name: Test
        run: cargo test --verbose --no-default-features --features "regexp lexical"

  bench:
    name: Bench
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: nightly

      - name: Compile bench
        run: cargo bench --verbose --no-run --features "regexp"

      - name: Run bench
        run: cargo bench --verbose --features "regexp"

  doc:
    name: Build documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: nightly

      - name: Build
        run: cargo doc --verbose --features "std lexical regexp"

  fmt:
    name: Check formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install rust
        uses: hecrj/setup-rust-action@v1
        with:
          components: rustfmt

      - run: cargo fmt -- --check
        continue-on-error: true

  coverage:
    name: Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install rust
        uses: hecrj/setup-rust-action@v1

      - name: Install cargo-tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Run cargo tarpaulin
        run: cargo tarpaulin
